### ISSUE TITLE
Using it on Quest 3 ?

### ISSUE THREAD

**Issue by gamersalpha** [jetstyle/Apple-Vision-Pro-UI-Kit-Demo#2]
hello, do u have a how to using it the demo on a quest 3 ?

thanks

**Comment by JetNik** [comment]
Hello! Yes, all works fine on Quest 3

**Comment by JetNik** [comment]
Hello, did you download the apk from the latest release and it doesn't work? Or you tried to build the apk and something went wrong?

**Comment by gamersalpha** [comment]
Sorry where is the apk for quest 3 and how to install it on quest 3 Thanks

**Comment by gamersalpha** [comment]
Hello, 
ok so i download the version here : 

https://github.com/jetstyle/Apple-Vision-Pro-UI-Kit-Demo/releases/tag/v1.2.0

look greats
