### ISSUE TITLE
Demo or readme for opening demo scene and building for Quest Pro?

### ISSUE THREAD

**Issue by ariestav** [jetstyle/Apple-Vision-Pro-UI-Kit-Demo#3]
Hello!

Thank you for putting together a kit and this demo scene.  It would be really helpful if you could include information about how to get started with the demo scene.  For example, a short tutorial on how to even open the correct asset.  It's not obvious for first-time Unity users.

Or, perhaps a video showing the actual process of downloading the project, opening it up and then building whatever export is necessary to open on the Quest.  Is there any information about how to do that anywhere?

Thanks again for putitng together these resources!

**Comment by ariestav** [comment]
Also, it seems like all the PNGs that are included in the repo are damaged?  Perhaps they are just encoded in a specific way that prevents them from being opened in macOS?

**Comment by JetNik** [comment]
Hi, in the [Releases ](https://github.com/jetstyle/Apple-Vision-Pro-UI-Kit-Demo/releases) section you can download the apk file of a particular release and put it on your Quest using the Side Quest app.
If you wanted to modify this demo, you need to clone this repository via git or via a visual environment for it (like Sourcetree).
If you download this repository as an archive, some large files (like textures) may be broken.

**Comment by JetNik** [comment]
I have updated the README with this information, thanks
