### ISSUE TITLE
Sliders demo

### ISSUE THREAD

**Issue by eugenner** [jetstyle/Apple-Vision-Pro-UI-Kit-Demo#4]
Could you please add some sliders to your demo? When I'm trying to add any slider by Unity menu (Vision UI / Sliders / Regular Slider) I've got a transparent bar with white square in the center and scale is 500 at that moment, so I should correct it to 1. Looks like it contains all the necessary elements, but they are not properly set. Also at the moment of inserting this component I got error in console:
```
NullReferenceException: Object reference not set to an instance of an object
JetXR.VisionUI.VisionControls.CreateRegularSlider (JetXR.VisionUI.VisionControls+Resources resources, System.Single height) (at Assets/JetXR/UI Kit For Vision Pro OS/Runtime/Scripts/VisionControls.cs:745)
JetXR.VisionUI.Editor.VisionMenuOptions.AddRegularSlider (UnityEditor.MenuCommand menuCommand) (at D:/MxFly/Unity-StarterSamples/Assets/JetXR/UI Kit For Vision Pro OS/Editor/VisionMenuOptions.cs:713)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32)
```
The other elements looks like working nice.

My Unity version is 2023.3.40f1.

**Comment by JetNik** [comment]
Hello, maybe you mean version 2022.3.40f1, unity doesn't have version 2023.3.40f1.

**Comment by eugenner** [comment]
Ups, my bad, the version is 2022.3.40f1. 
And one more thing, when I have installed the package UI Kit for Vision Pro OS, I still don't see it in the list of "Packages: in project" in the Package Manager of Unity. May be I did installation in a wrong way, but I tried couple of times.

**Comment by JetNik** [comment]
How do you install the package? Asset Store or git URL?

**Comment by eugenner** [comment]
From the Asset Store. But have to say that in the process of installation, the script was asking about installing additional packages:

com.unity.inputsystem@1.7.0
com.unity.textmeshpro@3.0.6
com.unity.ugui@1.0.0
com.unity.xr.interaction.toolkit@2.4.1

and I already have cople of them, but at first I did agree with the additional installation and that brokes my project, so after I had installed additional packages manually, and installing the UI Kit again choose the skip additional packages. Probably that is the reason... By the way com.unity.inputsystem@1.10.0 gives an error that I can't ignore, so I have to switch it back to 1.7.0 version. 

So now I have:
com.unity.inputsystem@1.7.0
com.unity.textmeshpro@3.0.9 <- little bit newer
com.unity.ugui@1.0.0
com.unity.xr.interaction.toolkit@2.5.4 <- little bit newer

**Comment by JetNik** [comment]
Can you remove the package folder and add the package using the git URL (https://github.com/jetstyle/Apple-Vision-Pro-UI-Kit.git)? I think we have some issues with the Asset Store version… Please let me know the results.

**Comment by JetNik** [comment]
Are other elements created correctly from the Vision UI menu?

**Comment by eugenner** [comment]
No. Looks like only elements that I can copy from the example are working correctly. I have to try to create a new project to reduce possible mistakes. Because I have added the package to existing one.

**Comment by eugenner** [comment]
Sorry, have missed your propose about reinstalling from GitHub. Yes, I have removed the folder Assets/JetXR and installed the package from git and now I can insert elements through the Unity menu. Thanks.

**Comment by JetNik** [comment]
Sorry about that, the asset store version will be fixed soon. The fix is now under review on the asset store portal.
By the way, the package should now be listed in the package manager.

**Comment by eugenner** [comment]
> By the way, the package should now be listed in the package manager.

Yes, it is.
